language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CONFIG=debug
  - CONFIG=release

addons:
  apt:
    packages:
      - build-essential
      - qt5-qmake
      - qtbase5-dev
      - qtbase5-dev-tools
      - libqt5opengl5-dev

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link qt5 --force ; fi

script: travis_wait bash -x ./Scripts/oneshot-${CONFIG}.sh
