language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - CONFIG=debug
  - CONFIG=release
matrix:
  exclude:
    - os: osx
      compiler: gcc
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libosmesa6-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libqt4-dev qt4-qmake; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt; fi
  - if test "x${TRAVIS_OS_NAME}" = "xlinux" ; then sudo apt install build-essential ; fi
script: travis_wait ./Scripts/oneshot-${CONFIG}.sh
notifications:
  slack:
    secure: D03l+Pzfk8TAQfvqVw0Cw1v4IBNxvG8u/RxZ4BJ349x4Ty8AzbJz0EfoXPYVjyPTn8tXaPLKFPmlZxORBj4wb6z9iqTWTi0LKZ+cKfIRIKFGJj10U4UcKss8LZupcBTbaLX1u8UrwrThlLuoJcU/pmpc/h0VldJxCvOIyGabCgs=
