language: cpp

dist: trusty
osx_image: xcode9.2
sudo: false

git:
  depth: 25

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CONFIG=debug
  - CONFIG=release

addons:
  apt:
    packages:
      - build-essential
      - qt5-qmake
      - qtbase5-dev
      - qtbase5-dev-tools
      - libqt5opengl5-dev

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link qt5 --force ; fi
  - if test "x${TRAVIS_OS_NAME}" == "xlinux" ; then
      export QT_BIN="/usr/lib/x86_64-linux-gnu/qt5/bin" ;
    fi

script: travis_wait source ./Scripts/oneshot-${CONFIG}.sh
